server:
  port: 3333

spring:
  cloud:
    gateway:
      routes:
      - id: Micro1
        uri: http://localhost:8082/
        predicates:
        - Path=/1
      - id: Micro2
        uri: http://localhost:8084/
        predicates:
        - Path=/2
        
  application:
    name: CLOUD-API-GATEWAY